package service

import (
	"context"
	"database/sql"
	"fmt"
	"sort"
	"time"

	source "sipemapars-etl/internal/models/source"
	warehouse "sipemapars-etl/internal/models/warehouse"
	"sipemapars-etl/internal/repository"
	"sipemapars-etl/internal/transformer"
	"sipemapars-etl/internal/utils"
)

type Service struct {
	sourceRepo    *repository.SourceRepository
	warehouseRepo *repository.WarehouseRepository
}

func New(sourceRepo *repository.SourceRepository, warehouseRepo *repository.WarehouseRepository) *Service {
	return &Service{
		sourceRepo:    sourceRepo,
		warehouseRepo: warehouseRepo,
	}
}

type patientMeta struct {
	DWID         int64
	SourceDietID int64
	DWRoomID     int64
	DWDietID     int64
}

func (s *Service) Run(ctx context.Context) error {
	fmt.Println("etl start")

	diets, err := s.sourceRepo.GetDiets(ctx)
	if err != nil {
		return fmt.Errorf("extract diets: %w", err)
	}
	rooms, err := s.sourceRepo.GetRooms(ctx)
	if err != nil {
		return fmt.Errorf("extract rooms: %w", err)
	}
	users, err := s.sourceRepo.GetUsers(ctx)
	if err != nil {
		return fmt.Errorf("extract users: %w", err)
	}
	menus, err := s.sourceRepo.GetMenus(ctx)
	if err != nil {
		return fmt.Errorf("extract menus: %w", err)
	}
	patients, err := s.sourceRepo.GetPatients(ctx)
	if err != nil {
		return fmt.Errorf("extract patients: %w", err)
	}
	transactions, err := s.sourceRepo.GetTransactions(ctx)
	if err != nil {
		return fmt.Errorf("extract transactions: %w", err)
	}

	if err := s.warehouseRepo.Reset(ctx); err != nil {
		return err
	}

	tx, err := s.warehouseRepo.BeginTx(ctx)
	if err != nil {
		return fmt.Errorf("begin warehouse tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	dietMap := map[int64]int64{0: 1}
	roomMap := map[int64]int64{0: 1}
	userMap := map[int64]int64{0: 1}
	menuMapBySourceDiet := map[int64]int64{0: 1}
	patientMetaBySourceID := map[string]patientMeta{}
	timeMap := map[string]int64{}

	if err := s.seedUnknownRows(ctx, tx); err != nil {
		return fmt.Errorf("seed unknown rows: %w", err)
	}

	if err := s.loadDiets(ctx, tx, diets, dietMap); err != nil {
		return fmt.Errorf("load diets: %w", err)
	}
	if err := s.loadRooms(ctx, tx, rooms, roomMap); err != nil {
		return fmt.Errorf("load rooms: %w", err)
	}
	if err := s.loadUsers(ctx, tx, users, userMap); err != nil {
		return fmt.Errorf("load users: %w", err)
	}
	if err := s.loadMenus(ctx, tx, menus, menuMapBySourceDiet); err != nil {
		return fmt.Errorf("load menus: %w", err)
	}
	if err := s.loadPatients(ctx, tx, patients, roomMap, dietMap, patientMetaBySourceID); err != nil {
		return fmt.Errorf("load patients: %w", err)
	}
	if err := s.loadTimes(ctx, tx, transactions, timeMap); err != nil {
		return fmt.Errorf("load time dimension: %w", err)
	}
	if err := s.loadFacts(ctx, tx, transactions, patientMetaBySourceID, menuMapBySourceDiet, timeMap); err != nil {
		return fmt.Errorf("load facts: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit warehouse tx: %w", err)
	}

	fmt.Println("etl done")
	return nil
}

func (s *Service) seedUnknownRows(ctx context.Context, tx *sql.Tx) error {
	now := time.Now()
	if err := s.warehouseRepo.InsertDiet(ctx, tx, warehouse.Diet{ID: 1, Name: "Unknown", Description: "Generated by ETL"}); err != nil {
		return err
	}
	if err := s.warehouseRepo.InsertRoom(ctx, tx, warehouse.Room{ID: 1, Name: "Unknown Room"}); err != nil {
		return err
	}
	if err := s.warehouseRepo.InsertUser(ctx, tx, warehouse.User{ID: 1, Name: "Unknown User", Email: "unknown@local", RoleID: 0}); err != nil {
		return err
	}
	if err := s.warehouseRepo.InsertMenu(ctx, tx, warehouse.Menu{ID: 1, Name: "Unknown Menu", Calories: 0, Price: 0, Status: 0}); err != nil {
		return err
	}
	if err := s.warehouseRepo.InsertPatient(ctx, tx, warehouse.Patient{
		ID:            1,
		Name:          "Unknown Patient",
		RoomID:        1,
		Gender:        0,
		Diagnosis:     "Unknown",
		AdmissionDate: time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC),
		Age:           0,
		BirthDate:     time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC),
		NIK:           "000000000000000",
		BirthPlace:    "Unknown",
		DietID:        1,
	}); err != nil {
		return err
	}
	if err := s.warehouseRepo.InsertTime(ctx, tx, warehouse.TimeDim{
		ID:            1,
		FullTimestamp: now,
		Date:          now,
		Day:           "Unknown",
		Month:         "00",
		Year:          "1970",
		Hour:          "00:00:00",
	}); err != nil {
		return err
	}
	return nil
}

func (s *Service) loadDiets(ctx context.Context, tx *sql.Tx, rows []source.Diet, dietMap map[int64]int64) error {
	nextID := int64(2)
	for _, row := range rows {
		if err := s.warehouseRepo.InsertDiet(ctx, tx, transformer.Diet(nextID, row)); err != nil {
			return err
		}
		dietMap[row.ID] = nextID
		nextID++
	}
	return nil
}

func (s *Service) loadRooms(ctx context.Context, tx *sql.Tx, rows []source.Room, roomMap map[int64]int64) error {
	nextID := int64(2)
	for _, row := range rows {
		if err := s.warehouseRepo.InsertRoom(ctx, tx, transformer.Room(nextID, row)); err != nil {
			return err
		}
		roomMap[row.ID] = nextID
		nextID++
	}
	return nil
}

func (s *Service) loadUsers(ctx context.Context, tx *sql.Tx, rows []source.User, userMap map[int64]int64) error {
	nextID := int64(2)
	for _, row := range rows {
		if err := s.warehouseRepo.InsertUser(ctx, tx, transformer.User(nextID, row)); err != nil {
			return err
		}
		userMap[row.ID] = nextID
		nextID++
	}
	return nil
}

func (s *Service) loadMenus(ctx context.Context, tx *sql.Tx, rows []source.Menu, menuMapBySourceDiet map[int64]int64) error {
	nextID := int64(2)
	for _, row := range rows {
		if err := s.warehouseRepo.InsertMenu(ctx, tx, transformer.Menu(nextID, row)); err != nil {
			return err
		}
		if _, exists := menuMapBySourceDiet[row.DietID]; !exists {
			menuMapBySourceDiet[row.DietID] = nextID
		}
		nextID++
	}
	return nil
}

func (s *Service) loadPatients(ctx context.Context, tx *sql.Tx, rows []source.Patient, roomMap, dietMap map[int64]int64, patientMetaBySourceID map[string]patientMeta) error {
	nextID := int64(2)
	for _, row := range rows {
		roomID := roomMap[row.RoomID]
		if roomID == 0 {
			roomID = 1
		}
		dietID := dietMap[row.DietID]
		if dietID == 0 {
			dietID = 1
		}
		if err := s.warehouseRepo.InsertPatient(ctx, tx, transformer.Patient(nextID, row, roomID, dietID)); err != nil {
			return err
		}
		patientMetaBySourceID[row.ID] = patientMeta{
			DWID:         nextID,
			SourceDietID: row.DietID,
			DWRoomID:     roomID,
			DWDietID:     dietID,
		}
		nextID++
	}
	return nil
}

func (s *Service) loadTimes(ctx context.Context, tx *sql.Tx, rows []source.Transaction, timeMap map[string]int64) error {
	seen := make(map[string]struct{})
	unique := make([]source.Transaction, 0, len(rows))
	for _, row := range rows {
		key := utils.TimestampKey(row.OrderDate)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		unique = append(unique, row)
	}
	sort.SliceStable(unique, func(i, j int) bool {
		if unique[i].OrderDate.Equal(unique[j].OrderDate) {
			return unique[i].ID < unique[j].ID
		}
		return unique[i].OrderDate.Before(unique[j].OrderDate)
	})
	nextID := int64(2)
	for _, row := range unique {
		key := utils.TimestampKey(row.OrderDate)
		timeMap[key] = nextID
		if err := s.warehouseRepo.InsertTime(ctx, tx, transformer.TimeDim(nextID, row.OrderDate)); err != nil {
			return err
		}
		nextID++
	}
	return nil
}

func (s *Service) loadFacts(ctx context.Context, tx *sql.Tx, rows []source.Transaction, patientMetaBySourceID map[string]patientMeta, menuMapBySourceDiet map[int64]int64, timeMap map[string]int64) error {
	nextID := int64(1)
	for _, row := range rows {
		meta, ok := patientMetaBySourceID[row.PatientID]
		if !ok {
			meta = patientMeta{DWID: 1, SourceDietID: 0, DWRoomID: 1, DWDietID: 1}
		}

		menuID := menuMapBySourceDiet[meta.SourceDietID]
		if menuID == 0 {
			menuID = 1
		}

		timeID := timeMap[utils.TimestampKey(row.OrderDate)]
		if timeID == 0 {
			timeID = 1
		}

		fact := transformer.FactTransaction(
			nextID,
			meta.DWID,
			menuID,
			meta.DWDietID,
			meta.DWRoomID,
			1,
			timeID,
			row.TotalPrice,
			1,
			row.Status,
		)
		if err := s.warehouseRepo.InsertFact(ctx, tx, fact); err != nil {
			return err
		}
		nextID++
	}
	return nil
}
